### PR TITLE
Fix pull_api mode

### PR DESCRIPTION
**Pull request by miv-ableton**
Hi! I'm new to this codebase, so hopefully these changes make sense. I was trying to use the pull_api mode, but found that it didn't work. With the changes here, I am able to make working Opus files using the pull mode.

See the commit comment for more details, and let me know if you have any further questions. Thanks!

### CODE REVIEW

**Comment by jmvalin** [comment]
Looks reasonable. I'll have a closer look and likely merge it (ping me if I don't). Just curious, are you using that API?

**Comment by miv-ableton** [comment]
At this point I'm just experimenting. I needed to use a specific filesystem layer, and the pull mode was the first thing I grabbed at to help me. I could probably switch over to the callback mode quite easily.

**Comment by miv-ableton** [comment]
Ping?

**Comment by jmvalin** [comment]
Thanks for the reminder. It's merged in master.

**Pull request closed without merging**
