### PR TITLE
fix ope_encoder_destroy() crash

### PR DESCRIPTION
**Pull request by dragos-oancea**

### CODE REVIEW

**Comment by jmvalin** [comment]
In what situation can this crash occur?

**Comment by dragos-oancea** [comment]
OggOpusEnc created with ope_encoder_create_pull() , ope_encoder_get_page() just returned 1 then I call ope_encoder_destroy() . But if I call ope_encoder_drain() before ope_encoder_destroy(), it does not happen . no callbacks.

**Comment by jmvalin** [comment]
Does that patch work instead:
https://jmvalin.ca/misc_stuff/fix_pull_api_close.patch

**Comment by dragos-oancea** [comment]
yes, it does!

**Comment by jmvalin** [comment]
Fixed in master. Thanks for reporting this.

**Pull request closed without merging**
